### ISSUE TITLE
tetrinet.c:571: 2 * off by one error ?

### ISSUE THREAD

**Issue by dcb314** [tatankat/gtetrinet#10]
Static analyser cppcheck says:

tetrinet.c:571:13: error: Width 128 given in format string (no. 8) is larger than destination buffer 'bfreq[128]', use %127s to prevent overflowing it. [invalidScanfFormatWidth]
tetrinet.c:571:13: error: Width 128 given in format string (no. 9) is larger than destination buffer 'sfreq[128]', use %127s to prevent overflowing it. [invalidScanfFormatWidth]

**Comment by tatankat** [comment]
Thanks for reporting! This should be fixed now.
